### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by AppleXY** [davide-belli/graphsage-diffpool-classifier#1]
hello，I have seen that your accuracy is very high, but I have some misunderstanding in your data's form.Could you please put your data into your project?Thanks a lot!

**Comment by davide-belli** [comment]
Hi, the dataset I used to test this simple network is MUTAG graph dataset. You can easily find it online and it is a pretty popular choice to benchmark models. In particular, the task is binary graph classification.

**Comment by AppleXY** [comment]
Thank you for your reply!It is helpful. Yuan Best wishes！------------------ 原始邮件 ------------------
发件人: "Davide"<notifications@github.com>
发送时间: 2019年7月14日(星期天) 晚上8:51
收件人: "davide-belli/graphsage-diffpool-classifier"<graphsage-diffpool-classifier@noreply.github.com>;
抄送: "AppleXY"<2899850137@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [davide-belli/graphsage-diffpool-classifier] dataset (#1)



Hi, the dataset I used to test this simple network is MUTAG graph dataset. You can easily find it online and it is a pretty popular choice to benchmark models. In particular, the task is binary graph classification.
 
&mdash;
